name = "telegram-alert-service"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 环境变量（通过 wrangler secret put 设置，或在 .dev.vars 中设置）
# TELEGRAM_BOT_TOKEN - 通过 wrangler secret put TELEGRAM_BOT_TOKEN 设置
# TELEGRAM_CHAT_ID - 通过 wrangler secret put TELEGRAM_CHAT_ID 设置

[env.production]
name = "telegram-alert-service"

[env.staging]
name = "telegram-alert-service-staging"

